### ISSUE TITLE
Ripple.js Module build failed: Error: Couldn't find preset  "es2015" relative to directory

### ISSUE THREAD

**Issue by clifmo** [petejohanson/vue-mdc#1]
Not much into Node and associated technologies. Just wanted to see an example of this library, but can't get it off the ground.

**Comment by petejohanson** [comment]
@clifmo Thanks for the interest. This library is in *very* early stages, and is really not ready for general use. You are welcome to check out the demo, and the necessary webpack configuration that was needed to get this "working" in `demo/simple-demo/build/webpack.base.conf.js`.

As this library (and the underlying material-components-web) matures, there will be more examples and documentation.

**Comment by paparent** [comment]
@clifmo Hi, I had the same issue. I submitted a fix. basically, you need to run `npm install` at the root folder. That should fix it !

**Comment by petejohanson** [comment]
@paparent Thanks for the PR.

I'm going to mark this closed. Better documentation is on the radar as this library matures.

Thanks!
